# -*- coding: utf-8 -*-
"""tomato_yolo_model_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YuIr5-a0HCzE26tfZ2JoF7wFD0TNwLWU
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5
# %cd yolov5
# %pip install -r requirements.txt
# %pip install -q roboflow
import torch
import os
from matplotlib import pyplot as plt
import cv2
import numpy as np
!pip install ultralytics
import ultralytics
from IPython.display import Image, clear_output
print(f"setup complete using torch {torch.__version__}({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'cpu'})")

from roboflow import Roboflow
rf = Roboflow(api_key="JeCixXyaJ4EAiLqhoItK", model_format= 'yolov5' , notebook= 'ultralytics')

os.environ["DATASET_DIRECTORY"] = "/content/datasets"

from roboflow import Roboflow
rf = Roboflow(api_key="JeCixXyaJ4EAiLqhoItK")
project = rf.workspace("andrea-podo-5nk2l").project("tomato-leaves-healthy-unhealthy-detection")
version = project.version(8)
dataset = version.download("yolov5")

!python train.py --img 416 --epochs 50 --data {dataset.location}/data.yaml --weights yolov5n.pt --cache

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir runs

!python detect.py --weights /content/yolov5/runs/train/exp/weights/best.pt --img 416 --conf 0.7 --source {dataset.location}/valid/images

from google.colab import files
files.download("/content/yolov5/runs/train/exp/weights/best.pt")

